# Generated by Django 2.2.10 on 2020-03-14 15:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='지역구 이름')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='정적수')),
            ],
            options={
                'verbose_name': '지역구',
                'verbose_name_plural': '지역구',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=20, verbose_name='시군구이름')),
                ('town', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='읍면동명'), default=list, size=None)),
                ('state', models.CharField(max_length=20, verbose_name='지역 이름')),
                ('district', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='district.District', verbose_name='지역구')),
            ],
        ),
    ]
