# Generated by Django 2.2.10 on 2020-04-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_district_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='active_19',
            field=models.BooleanField(default=False, verbose_name='Is 19 district'),
        ),
        migrations.AddField(
            model_name='district',
            name='active_20',
            field=models.BooleanField(default=False, verbose_name='Is 20 district'),
        ),
        migrations.AddField(
            model_name='district',
            name='active_21',
            field=models.BooleanField(default=False, verbose_name='Is 21 district'),
        ),
    ]
