# Generated by Django 2.2.10 on 2020-03-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLawMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_id', models.CharField(choices=[('19', '19대'), ('20', '20대')], max_length=10)),
                ('vote_count', models.CharField(blank=True, max_length=10, verbose_name='득표수')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('name_en', models.CharField(blank=True, max_length=20, verbose_name='영어 이름')),
                ('name_cn', models.CharField(blank=True, max_length=20, verbose_name='한자 이름')),
                ('gender', models.CharField(choices=[('m', '남성'), ('f', '여성'), ('n', '중성'), ('x', '표기안함')], max_length=10)),
                ('party', models.CharField(blank=True, max_length=10, verbose_name='정당')),
                ('birthday', models.CharField(blank=True, max_length=8)),
                ('education', models.TextField(blank=True, verbose_name='학력정보')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
                ('career', models.CharField(blank=True, max_length=255, verbose_name='커리어')),
                ('image', models.FileField(blank=True, null=True, upload_to='person/', verbose_name='이미지 파일')),
                ('twitter', models.CharField(blank=True, max_length=20)),
                ('facebook', models.CharField(blank=True, max_length=20)),
                ('blog', models.CharField(blank=True, max_length=255)),
                ('page', models.CharField(blank=True, max_length=255)),
                ('wiki', models.TextField(blank=True, verbose_name='추가 정보')),
                ('extra_info', models.TextField(blank=True, verbose_name='추가 정보')),
                ('type', models.CharField(choices=[('R', '비례'), ('D', '지역구')], max_length=10)),
                ('active', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawmaker.ActiveLawMaker', verbose_name='현역의원')),
                ('district', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='district.District', verbose_name='지역구')),
            ],
            options={
                'verbose_name': '지역구',
                'verbose_name_plural': '지역구',
            },
        ),
    ]
