# Generated by Django 2.2.10 on 2020-03-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='job',
            field=models.CharField(blank=True, max_length=20, verbose_name='직업'),
        ),
    ]
