# Generated by Django 2.2.10 on 2020-03-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaker', '0002_person_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelawmaker',
            name='vote_count',
            field=models.CharField(blank=True, max_length=30, verbose_name='득표수'),
        ),
    ]
