# Generated by Django 2.2.10 on 2020-03-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaker', '0003_auto_20200329_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='facebook',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='job',
            field=models.CharField(blank=True, max_length=30, verbose_name='직업'),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
