# Generated by Django 2.2.10 on 2020-04-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaker', '0004_auto_20200329_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='이미지 url'),
        ),
    ]
