# Generated by Django 2.2.10 on 2020-04-05 13:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaker', '0005_person_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelawmaker',
            name='Approval_bill',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activelawmaker',
            name='proposer_bill',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=[], size=None),
            preserve_default=False,
        ),
    ]
