# Generated by Django 2.2.10 on 2020-04-05 14:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaker', '0006_auto_20200405_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activelawmaker',
            name='Approval_bill',
        ),
        migrations.AddField(
            model_name='activelawmaker',
            name='approval_bill',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=[], max_length=20), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activelawmaker',
            name='proposer_bill',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=[], max_length=20), size=None),
        ),
    ]
