# Generated by Django 2.2.10 on 2020-04-06 14:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaker', '0009_activelawmaker_representative_approval_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelawmaker',
            name='attend_rate',
            field=models.CharField(blank=True, max_length=8, verbose_name='재산'),
        ),
        migrations.AddField(
            model_name='activelawmaker',
            name='committee_attend_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, max_length=8, null=True, verbose_name='위원회 출석정보'),
        ),
        migrations.AddField(
            model_name='activelawmaker',
            name='peoplepower21_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='재산'),
        ),
        migrations.AddField(
            model_name='activelawmaker',
            name='property',
            field=models.CharField(blank=True, max_length=12, verbose_name='재산'),
        ),
    ]
