# Generated by Django 2.2.10 on 2020-04-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaker', '0011_auto_20200407_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidacy',
            name='candidacy_count',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='현재채납급액'),
            preserve_default=False,
        ),
    ]
