# Generated by Django 2.2.10 on 2020-04-07 16:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaker', '0013_auto_20200407_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelawmaker',
            name='ranking',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='랭킹'),
        ),
    ]
