# Generated by Django 2.2.10 on 2020-04-07 16:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaker', '0014_activelawmaker_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelawmaker',
            name='analysis_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='대표발의법안분석'),
        ),
    ]
