# Generated by Django 2.2.10 on 2020-04-09 17:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaker', '0015_activelawmaker_analysis_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelawmaker',
            name='major_bill_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='주요법안 찬반투표'),
        ),
        migrations.AlterField(
            model_name='activelawmaker',
            name='analysis_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='대표발의 법안분석'),
        ),
    ]
