# Generated by Django 2.2.10 on 2020-04-09 18:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaker', '0016_auto_20200409_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelawmaker',
            name='major_bill_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
