# Generated by Django 2.2.10 on 2020-04-09 18:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaker', '0017_auto_20200409_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activelawmaker',
            name='major_bill_info',
        ),
        migrations.AddField(
            model_name='activelawmaker',
            name='major_bills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=[], max_length=255), default=[], size=None),
            preserve_default=False,
        ),
    ]
