# Generated by Django 2.2.10 on 2020-04-09 18:26

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaker', '0018_auto_20200409_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activelawmaker',
            name='major_bills',
        ),
        migrations.AddField(
            model_name='activelawmaker',
            name='major_bill',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
